steps:
- name: 'gcr.io/cloud-builders/docker'
  timeout: 86400s
  args: [ 'build', '-t', 'gcr.io/playground-s-11-51032b87/dockerfile', '.' ]
  timeout: 86400s
timeout: 86400s
options:
  pool:
    name: 'projects/playground-s-11-51032b87/locations/southamerica-east1/workerPools/southamerica-east1'  
    










