steps:
- name: 'gcr.io/cloud-builders/docker'
  timeout: 86400s
  args: [ 'build', '-t', 'gcr.io/playground-s-11-ed63077b/dockerfile', '.' ]
  timeout: 86400s
timeout: 86400s
options:
  pool:
    name: 'projects/playground-s-11-ed63077b/locations/asia-southeast1/workerPools/southeast1'  
    










